# This is a basic workflow to help you get started with Actions

name: Build Swagger Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      dockerTagVersion:
        description: 'Docker tag version to use'
        required: true
        default: 'latest'
      isProduction:
        description: "Is this a production release?"
        type: boolean
        required: true

jobs:
  # Run unit-tests on all branches and releases
  release:
    runs-on: [self-hosted, dgpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: rake test